name = "All the Mods 10"
author = "ATMTeam"
version = "4.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99877e4582a8a2806b40bb5aec10df6e5619a6f8ed98ce153ba8444b139a861c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
