name = "All the Mods 10"
author = "ATMTeam"
version = "4.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79967d9a603b369818aeb038e4eb7de037b7827c5107ebc9c521545c86f40392"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
